a = input('Escreva algo: ')
print('o tipo primitivo desse valor é ', type(a))
print('Só tem espaços? ',a.isspace())
print('É um número?: ',a.isnumeric())
print('É alfabetico? ',a.isalpha())
print('É alfanúmrico? ',a.isalnum())
print('Está em maiúscula?',a.isupper())
print('Está em minúscula? ',a.islower())
print('Está capitalizada? ',a.istitle())
